#!/bin/bash

# matar todos los procesos y
# eliminar archivos con ctrl + c
# liberacion de recursos y eliminacion de archivos temporales
cleanup() {
    echo "Cleaning up..."
    rm -f "$video_pipe"
    rm -f "$audio_ready" "$ffmpeg_started" "$video_started"
    kill 0 2>/dev/null
}
trap cleanup EXIT SIGINT

# localizacion de pipes
pipes_dir="temp/pipes"
video_pipe="temp/pipes/video_pipe"
# localizacion de flags
flags_dir="temp/flags"
audio_ready="temp/flags/audio_ready.flag"
ffmpeg_started="temp/flags/ffmpeg_started.flag"
video_started="temp/flags/video_started.flag"
# localizacion de renderer
video_generator="video-generator/build/video_generator"
# lacalizacion de sintetizador
audio_generator="audio-generator/script.scd"
# localizacion de output
output="test/output.mp4"

# eliminar pipes
rm -f "$video_pipe"
# eliminar archivos de prueba
rm -f "$output"
# eliminar flags
rm -f "$audio_ready"
rm -f "$ffmpeg_started"
rm -f "$video_started"

# crear directorios temporales
if [ ! -d "$pipes_dir" ]; then
    mkdir -p "$pipes_dir"
fi
if [ ! -d "$flags_dir" ]; then
    mkdir -p "$flags_dir"
fi

# crear pipes
mkfifo "$video_pipe"

# Iniciar servidor JACK solo en Linux
if [[ "$OSTYPE" != "darwin"* ]]; then 
    jackd -d dummy -r 48000 -p 512 &
    sleep 2
fi

# inciciar script superCollider
# que inicia servidor y espera a que comience la generacion de video
sclang "$audio_generator" &

while [ ! -f "$audio_ready" ]; do
    sleep 0.1
done

# abrir generador de video en el background
# que espera a que ffmpeg comience para generar video
"$video_generator" > "$video_pipe" &

touch "$ffmpeg_started"

# generacion de video y conversion de vfr a cfr
ffmpeg \
-fflags +genpts \
-thread_queue_size 512 -f rawvideo -framerate 30 -pix_fmt rgba -video_size 400x300 -i "$video_pipe" \
-thread_queue_size 512 -f avfoundation -i ":BlackHole 2ch" \
-map 0:v:0 -map 1:a:0 \
-vf "vflip" -r 30 -vsync cfr \
-af "aresample=async=1:first_pts=0" \
-f flv -c:v libx264 -pix_fmt yuv420p -b:v 400k \
-c:a aac -ar 48000 -b:a 128k \
rtmp://a.rtmp.youtube.com/live2/caee-596b-76td-tv9k-8g21

# test.mp4


#-listen 1 rtmp://localhost:1935/test

# ffplay rtmp://localhost:1935/test


# -map 0:v:0 -map 1:a:0 \

# -c:v libx264 -pix_fmt yuv420p \
# -c:a aac -ar 48000 \
# test.mp4

# -thread_queue_size 512 -f avfoundation -i ":1" \

# ffmpeg \
# -thread_queue_size 512 -f rawvideo -pix_fmt rgba -video_size 400x300 -use_wallclock_as_timestamps 1 -i "$video_pipe" \
# -thread_queue_size 512 -f avfoundation -i ":1" \
# -vf "vflip" -r 30 \
# -c:v libvpx-vp9 -deadline realtime -cpu-used 8 -row-mt 1 -pix_fmt yuv420p -b:v 800k -g 30 \
# -c:a libopus -ar 48000 -b:a 128k \
# -f webm -cluster_size_limit 2M -content_type video/webm \
# -listen 1 http://127.0.0.1:8080/stream.webm
